import { NextResponse } from "next/server";

/**
 * /.well-known/security.txt — the standard way to publish a security
 * contact for vulnerability reports. Referenced by:
 *   https://securitytxt.org/
 *   https://www.rfc-editor.org/rfc/rfc9116
 *
 * Vercel serves this from `app/.well-known/security.txt/route.ts`
 * because the `/.well-known/` path is reserved for metadata by RFC 8615
 * and a `route.ts` inside it produces a typed JSON response at the
 * parent path. Using a route handler here instead of a static file
 * means we can update it without redeploying.
 */
export const dynamic = "force-static";
export const revalidate = 3600;

export function GET() {
  const body = `# Anamata Kāhui security contact
# Generated by /app/.well-known/security.txt/route.ts
# See https://www.rfc-editor.org/rfc/rfc9116 for format.

Contact: mailto:security@anamatakahui.co.nz
Contact: https://github.com/LaFinnix/anamata-kahui/security/advisories
Expires: 2027-12-31T23:59:59Z
Encryption: https://github.com/LaFinnix/anamata-kahui/security/policy
Acknowledgments: https://anamatakahui.co.nz/transparency
Preferred-Languages: en, mi
Canonical: https://anamatakahui.co.nz/.well-known/security.txt

# Policy: We aim to acknowledge reports within 5 working days and
# provide a remediation timeline within 10 working days. Coordinated
# disclosure is welcome; we will credit reporters (unless requested
# otherwise).
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
